name: Build Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Setup OpenGL for Runner
      uses: openrndr/setup-opengl@v1.1
    - name: OpenGL Info
      run: xvfb-run glxinfo
    - uses: actions/checkout@v2
    - name: Build
      run: make build
    
