name: Tests

on:
  push:
    branches: [master]

jobs:
  build_22:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Test
        run: make test
